#!/usr/bin/env python
# -*- coding: utf-8 -*-

# dict that has the necessary aliases for tiehallinto.fi cgi-script locations
matka_aliases = {
    "Heinola": "Heinola (yhdistetty)",
    "Porvoo": "Porvoo (yhdistetty)",
    "Lohja": "Lohja (yhdistetty)",
    "Suomussalmi": "Suomussalmi, kko.",
    "Utsjoki": "Utsjoki, Utsjoki",
    "Värtsilä": "Värtsilä kko",
    "Kaaresuvanto": "Enontekiö, Kaaresuvanto",
    "Kilpisjärvi": "Enontekiö, Kilpisjärvi",
    "Kivilompolo": "Enontekiö, Kivilompolo",
    "Palojoensuu": "Enontekiö, Palojoensuu",
    "Inari": "Inari kko",
    "Ivalo": "Inari, Ivalo",
    "Näätämö": "Inari, Näätämö",
    "Raja-jooseppi": "Inari, Raja-Jooseppi",
    "Repojoki": "Inari, Repojoki",
    "Säynätsalo": "Jyväskylä, Säynätsalo",
    "Palokka": "Jyväskylän mlk, Palokka",
    "Tikkakoski": "Jyväskylän mlk, Tikkakoski",
    "Vaajakoski": "Jyväskylän mlk, Vaajakoski",
    "Kaipola": "Jämsä, Kaipola",
    "Haapamäki": "Keuruu, Haapamäki",
    "Vartius": "Kuhmo, Vartius, raja",
    "Riistavesi": "Kuopio, Riistavesi",
    "Nuijamaa": "Lappeenranta, Nuijamaa",
    "Lappi": "Lappi tl",
    "Lievestuore": "Laukaa, Lievestuore",
    "Koli": "Lieksa, Koli",
    "Otava": "Mikkeli, Otava",
    "Raippaluoto": "Mustasaari, Raippaluoto",
    "Meri-pori": "Pori, Meri-Pori",
    "Meltaus": "Rovaniemen mlk, Meltaus",
    "Pirttikoski": "Rovaniemen mlk, Pirttikoski",
    "Vuojärvi": "Sodankylä, Vuojärvi",
    "Vuotso": "Sodankylä, Vuotso",
    "Sukeva": "Sonkajärvi, Sukeva",
    "Ämmänsaari": "Suomussalmi, Ämmänsaari",
    "Tenhola": "Tammisaari, Tenhola",
    "Tuuri": "Töysä, Tuuri",
    "Karigasniemi": "Utsjoki, Karigasniemi",
    "Nuorgam": "Utsjoki, Nuorgam",
    "Kalanti": "Uusikaupunki, Kalanti",
    "Vaalimaa": "Virolahti, Vaalimaa, raja",
    "Niirala": "Värtsilä, Niirala, raja",
    "Konginkangas": "Äänekoski, Konginkangas"
    }
